name:                query-parser
version:             0.1.0.0
github:              "foxhuston/query-parser"
license:             BSD-3-Clause
author:              "Fox Huston"
maintainer:          "448633+foxhuston@users.noreply.github.com"
copyright:           "(c) 2024 Fox Huston"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/foxhuston/query-parser#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  default-extensions:
    - DeriveFunctor
    - DeriveFoldable
    - DeriveTraversable
    - TypeFamilies
  dependencies:
    - megaparsec
    - containers
    - scientific
    - recursion-schemes
    # - text

executables:
  query-parser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - query-parser

tests:
  query-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - query-parser
    - megaparsec
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    # - falsify
